.PHONY: clean All

All:
	@echo "----------Building project:[ Gatherer - Debug ]----------"
	@"$(MAKE)" -f  "Gatherer.mk"
clean:
	@echo "----------Cleaning project:[ Gatherer - Debug ]----------"
	@"$(MAKE)" -f  "Gatherer.mk" clean
